global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "spring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: 'vminsert'
    static_configs:
      - targets: ['vminsert:8480']
  - job_name: 'vmselect'
    static_configs:
      - targets: ['vmselect-1:8481', 'vmselect-2:8481']
  - job_name: 'vmstorage'
    static_configs:
      - targets: ['vmstorage-1:8482', 'vmstorage-2:8482']